name: nikah_forever_assignment
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1


environment:
  sdk: ^3.5.3

#Dependencies
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  pinput: ^5.0.0
  intl: ^0.19.0
#Dev dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true
  #assets
  assets:
    - assets/icons/
 